import Head from "next/head";
import { useRouter } from 'next/router';
import styles from "@/styles/Home.module.css";

const DISCOGRAPHIES = [
  {
    cle: 'album',
    nom: 'Albums',
    icone: '⚛️',
    couleur: '#fcff64',
    description: 'Une release officiel d\'un groupe de musique.',
  },
  {
    cle: 'ep',
    nom: 'EPs',
    icone: '▲',
    couleur: '#fc4d7f',
    description: 'Presque un album, un chapitre d\'une histoire.',
  },
  {
    cle: 'single',
    nom: 'Singles',
    icone: '💚',
    couleur: '#5d3bd0',
    description: 'La lumière d\'un album ou une étincelle dans un le spectacle de la créativité musicale.',
  },
  {
    cle: 'demo',
    nom: 'Demos',
    icone: '💚',
    couleur: '#90cd3b',
    description: 'Projet souvent pas terminé et la lumière d\'un projet polie.',
  }
]

export default function Home() {
  const routeur = useRouter();

  function choisirDiscographie(cle) {
    localStorage.setItem('discographieChoisie', cle);
    routeur.push('/album');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="accueil-grille">
        {DISCOGRAPHIES.map((discographie, i) => (
          <div
            key={discographie.cle}
            className={styles.main}
            onClick={() => choisirDiscographie(discographie.cle)}
            style={{
              background: discographie.fondGradient,
              animation: `monterDouceur 0.6s ease-out ${i * 0.15}s both`
            }}
          >
            <div className="accueil-carte-icone" style={{ color: discographie.couleur }}>
              {discographie.icone}
            </div>
            <h2 className="accueil-carte-nom" style={{ color: discographie.couleur }}>
              {discographie.nom}
            </h2>
            <p className="accueil-carte-description">
              {discographie.description}
            </p>
            <div className="accueil-carte-action" style={{ borderColor: discographie.couleur, color: discographie.couleur }}>
              Explorer les fiches →
            </div>
          </div>
        ))}
      </div>

      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <div className={styles.intro}> </div>
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Deploy Now
            </a>
            <a
              className={styles.secondary}
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
